### ISSUE TITLE
[QUESTION] embeds link and embeds folder

### ISSUE THREAD

**Issue by afterdelight** [AlphaSlayer1964/kemono-dl#105]
after newest update, what about embeds links structure and embeds folder default sturcture? are they still the same?
i only found setting for inline folder

**Comment by AlphaSlayer1964** [comment]
embeds text was merged into post consent with comments, I realize now the links should be added to links.txt. I have not got around to adding yt-dlp implemented to download the embed.

**Comment by afterdelight** [comment]
the previous version has a embed folder and embed .txt files inside the download folder
![image](https://user-images.githubusercontent.com/39585663/166142106-b04f8721-b2d0-466e-ad37-9391336e807c.png)
please add it back

**Comment by AlphaSlayer1964** [comment]
There is no point in having the embed title, link, and description in its own file and not just in the post content. I will need to add when a links.txt file is requested it includes the embed link.

**Comment by afterdelight** [comment]
well, i just realized the embeds links are not very important so you can skip that feature. is --yt-dlp command already working and are the downloads goes to embed folder?

**Comment by AlphaSlayer1964** [comment]
--yt-dlp is currently disabled. I still need to add an option to pass your own yt_dlp options.

**Comment by afterdelight** [comment]
how to enable it back temporarily i just want to download the embeds with default yt-dlp args, i just need an -output arg enabled.
