### ISSUE TITLE
[Feature Request] - Short media into folders according to the type of the media they are

### ISSUE THREAD

**Issue by Sohzph** [AlphaSlayer1964/kemono-dl#106]
### Description

Please add a function that allows to download the posts without them being inside folders and that instead they are sorted into folders according to the type of media they are (images, videos etc.)

After I finish downloading everything, I have to extract all the images from all the folders, then create normally two folders (for images and for videos) manually and it would be great if all this was done automatically.

### Additional comments

It is not a development priority but it would certainly do a great favor to the user's quality of life :)

**Comment by afterdelight** [comment]
just remove {title} from directory pattern. it will partially solve your problem

**Comment by Sohzph** [comment]
> just remove {title} from directory pattern. it will partially solve your problem

Where's the directory pattern?

**Comment by afterdelight** [comment]
show me your arguments setting

**Comment by Sohzph** [comment]
> show me your arguments setting

I didn't put any arguments, I just ran it from a PS terminal, something like: 

`PS C:\Users\sohzp\AppData\Local\kemono-dl> python kemono-dl.py --cookies "cookie.txt" --links https://kemono.party/...`

**Comment by afterdelight** [comment]
add this argument --dirname-pattern {site}/{service}/{username} [{user_id}]
Now it will download to one profile folder only and doesnt have subfolders

**Comment by Sohzph** [comment]
> add this argument --dirname-pattern {site}/{service}/{username} [{user_id}] Now it will download to one profile folder only and doesnt have subfolders

Thanks, but it gives me an error: 

```
python.exe : The command parameter has already been specified.
On line: 1 Character: 1
+ python kemono-dl.py --cookies "coomer.party_cookies.txt" --links http ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo : InvalidArgument: (:) [], ParameterBindingException
    + FullyQualifiedErrorId : ParameterSpecifiedAlready
```

**Comment by afterdelight** [comment]
sorry i meant
--dirname-pattern "{site}/{service}/{username} [{user_id}]"

forgot to add the quotes

**Comment by afterdelight** [comment]
on what os are you

**Comment by Sohzph** [comment]
> sorry i meant --dirname-pattern "{site}/{service}/{username} [{user_id}]"
> forgot to add the quotes
It worked "more or less", but those 29837237823 folders are still there. I would like that inside the creator's folder all the images and videos are already there.
![image](https://user-images.githubusercontent.com/94597840/166147902-86865e93-4ffd-4eab-985d-32651c35fce7.png)
> on what os are you
I'm on Windows, but I've used this in Ubuntu as well.

**Comment by afterdelight** [comment]
add more of this --filename-pattern "[{published}] [{id}] [{index}] {filename}.{ext}"

**Comment by afterdelight** [comment]
or you can download my fork and replace the file in your src folder

https://github.com/afterdelight/kemono-dl/blob/set-default-arguments/src/args.py

now no need to add folders and filenames arguments. only need cookies and link arguments.

**Comment by Sohzph** [comment]
> add more of this --filename-pattern "[{published}] [{id}] [{index}] {filename}.{ext}"

Thanks, now it works 👍 

> or you can download my fork and replace the file in your src folder
> 
> https://github.com/afterdelight/kemono-dl/blob/set-default-arguments/src/args.py
> 
> now no need to add folders and filenames arguments. only need cookies and link arguments.

I prefer the arguments, your version downloads .json and .html files xd I just want the images and videos.

**Comment by afterdelight** [comment]
well you can set download json and content from true to false in
https://github.com/afterdelight/kemono-dl/blob/set-default-arguments/src/args.py

**Comment by AlphaSlayer1964** [comment]
This is not a feature I will be adding. I recommend to use the filename patterns to download everything to a single folder and using the windows file explorer to sort by extensions.
