### ISSUE TITLE
getting `too many 429 error responses` on almost every file I try to download

### ISSUE THREAD

**Issue by 4skinsandwich** [AlphaSlayer1964/kemono-dl#107]
[debug.log](https://github.com/AlphaSlayer1964/kemono-dl/files/8606571/debug.log)

### Version

Version: 2022.04.27

### Your Command

py kemono-dl.py --cookies "cookie.txt" --links https://kemono.party/patreon/user/2885342

### Description of bug

the link in the command above goes to tofu bear's page, when I tried downloading from there a few files got correctly downloaded but a majority of files were met with error 429 after trying to download the file multiple times and failing.

### How To Reproduce

The bug consistently shows up for almost every file I try to download from just about any artist. I moved the files I downloaded a few days ago when the script worked perfectly and it was met with the same errors when I tried again

### Error messages and tracebacks

![unknown](https://user-images.githubusercontent.com/104613217/166342649-715de458-2cb2-470d-9d73-630d53f1544e.png)

**Comment by AlphaSlayer1964** [comment]
429 means the server is rate limiting you. Try creating a new cookie file. Try using a VPN. Try waiting a an hour or more.

**Comment by 4skinsandwich** [comment]
thank you
