### ISSUE TITLE
Getting Some Errors That Look Like This

### ISSUE THREAD

**Issue by ninko76** [AlphaSlayer1964/kemono-dl#108]
### Version

2022.04.28

### Your Command

```bash

py kemono-dl.py --cookies "cookie.txt" --links https://kemono.party/patreon/user/990234

```

### Description of bug

Lots of errors.

### How To Reproduce

Enter the command again.

### Error messages and tracebacks

```python

![Screenshot 2022-05-02 194504](https://user-images.githubusercontent.com/103625285/166399764-f5750263-dae8-488d-be07-7ae706a0573b.png)

```

### Additional comments

[debug.log](https://github.com/AlphaSlayer1964/kemono-dl/files/8608081/debug.log)

**Comment by AlphaSlayer1964** [comment]
Error 429 means you are getting rate limited. Please try redownloading your cookies, using a VPN, or wait a bit before downloading again.  

I will also be looking into see why people are now getting so many 429 errors now.

**Comment by ninko76** [comment]
mkay
