### ISSUE TITLE
Module not found error

### ISSUE THREAD

**Issue by CakeFacee** [AlphaSlayer1964/kemono-dl#109]
<img width="926" alt="Screen Shot 2022-05-03 at 3 44 35 pm" src="https://user-images.githubusercontent.com/10666318/166409237-1bbd13c6-17e7-4f59-9244-9dbaa46b62c9.png">
Keep getting "ModuleNotFoundError: No module named 'requests'"
Running the script on macOS with python3

**Comment by AlphaSlayer1964** [comment]
did you install the requirements?

**Comment by afterdelight** [comment]
pip install requests
