### ISSUE TITLE
[QUESTION] Is the --update-posts option using json files obsolete?

### ISSUE THREAD

**Issue by q36yznmh** [AlphaSlayer1964/kemono-dl#111]
**--archive FILE Options**
Can't dl the post when it is updated.

**Duplicate check using hash**
If the zip file is extracted, the original zip file must be left behind or it will be downloaded again.
The same is true if unnecessary images are deleted.

I want to download only the content of updated posts, even if I have deleted unnecessary files.

**Comment by afterdelight** [comment]
maybe use the older veriosn will works

**Comment by afterdelight** [comment]
the posts are rarely update so just use --archive option

**Comment by AlphaSlayer1964** [comment]
Yes the update option is removed for the time being. 
The checks you describe are not duplicate checks. The program makes sure you have all the files from the post downloaded if you don't want it re downloading files use the `--archive FILE` to have it log the post as completed.
