### ISSUE TITLE
add archive filename template  

### ISSUE THREAD

**Issue by afterdelight** [AlphaSlayer1964/kemono-dl#114]
### Description
add archive filename template  such as {username}_{service}_downloaded.txt
will result in gin00_fanbox_downloaded.txt

### Additional comments
it will be easier to sort downloaded contents

**Comment by AlphaSlayer1964** [comment]
The archive file is just a place to store completed posts I don't see how this would be useful to have separate archive files and it would add un needed complexity finding the archive file.

**Comment by afterdelight** [comment]
its because i have more than 100 artists to download, with the archive filename template i can check easily which user has already been downloaded to log file.

can you guide me which file to modify i tried to modify args.py but it gives me
'{username} {service} downloaded.txt' and not, for example: gin00 fanbox downloaded.txt
