### ISSUE TITLE
Files not retrieved when it's attached in Content but not Files section

### ISSUE THREAD

**Issue by 0o0miku0o0** [AlphaSlayer1964/kemono-dl#118]
### Version
2022.04.27

### Your Command
python kemono-dl.py --cookies "cookie.txt" --links https://kemono.party/fanbox/user/93583/post/1252706 --verbose

### Description of bug
Files not retrieved when it's attached in Content but not Files section

### How To Reproduce
Just run the command and no file is downloaded, folder is also not created.

Check post with this issue: https://kemono.party/fanbox/user/93583/post/1252706
The post contain several images but are not downloaded.
Press F12 to check HTML, images are in 'div class="post__content"' with 'img'
<img width="216" alt="2" src="https://user-images.githubusercontent.com/61375381/172439472-b3784fe4-1a00-44c5-a2f4-8d479054f4b0.png">

Then compare with another post that works fine: https://kemono.party/fanbox/user/93583/post/3915707
Press F12 to check HTML, images are in 'div class="post__files"' with 'div class="post__thumbnail"'
<img width="236" alt="1" src="https://user-images.githubusercontent.com/61375381/172440281-def1f561-41da-42af-a9d8-3a96f1a455cc.png">

In addition, the images in first post 1252706 has extra long file name, for example: ff6d54522d0eb01c8d918442b11a0b6e8b7af2118e9f1036ad28f068a9b70084.png

### Error messages and tracebacks
<img width="784" alt="screenshot" src="https://user-images.githubusercontent.com/61375381/172440697-cb724fb8-9493-4445-b637-4640ee4214b8.png">

### Additional comments
I assume that the HTML structure difference has caused this issue but not for sure.

**Comment by AlphaSlayer1964** [comment]
Those images are inline images in the post content. You must use the `--inline` flag to download those images.

**Comment by 0o0miku0o0** [comment]
Thanks a lot for the hint.
