### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by MisterQX** [AlphaSlayer1964/kemono-dl#141]
Today i try to download a link of kemono but i receive this error:

ERROR:Failed to download: 1.jpg | 403 Forbidden
INFO:Downloading: 2.jpg
ERROR:Failed to download: 2.jpg | 403 Forbidden
INFO:Downloading: 3.jpg
ERROR:Failed to download: 3.jpg | 403 Forbidden
INFO:Downloading: 4.jpg
ERROR:Failed to download: 4.jpg | 403 Forbidden
INFO:Downloading: 5.jpg
ERROR:Failed to download: 5.jpg | 403 Forbidden

Some files can be downloaded successfully, some files will pop up this error

**Comment by ovear** [comment]
Should fix now

Please try https://github.com/ovear/kemono-dl

**Comment by MisterQX** [comment]
> 现在应该修
> 
> 请尝试https://github.com/ovear/kemono-dl

It works now, thanks for your help

**Comment by IcedCoffeel** [comment]
> 现在应该修
> 
> 请尝试https://github.com/ovear/kemono-dl

您好，我以前一直使用的22年2月份版本，那个版本下载下来的文件数字编号文件数超过2位都是[01]_的前缀，新的main下载之后不管文件总数多少都是[1]_前缀，导致以前下载过的不能自动检测，全部重新下载了一遍，请问如何可以更改命名规则？
还有新版本的不会自动下载comments和content，请问如何修改可以让脚本像以前一样能自动把这两个下载下来？

**Comment by ovear** [comment]
这些默认行为我都没有修改，你可能用的是其他人修改过的版本。
命名规则，下载的内容都可以在启动的时候指定，可以看一下readme。

> > 现在应该修
> > 请尝试https://github.com/ovear/kemono-dl
> 
> 您好，我以前一直使用的22年2月份版本，那个版本下载下来的文件数字编号文件数超过2位都是[01]_的前缀，新的main下载之后不管文件总数多少都是[1]_前缀，导致以前下载过的不能自动检测，全部重新下载了一遍，请问如何可以更改命名规则？ 还有新版本的不会自动下载comments和content，请问如何修改可以让脚本像以前一样能自动把这两个下载下来？
