### ISSUE TITLE
error while running kemono script

### ISSUE THREAD

**Issue by ubantos2** [AlphaSlayer1964/kemono-dl#149]
I am using windows 11
Installed python 3.10.7
installed py -m pip install -r requirements.txt  
added cookies.txt in the same location as the script.

when i run the script, its throwing below error
![image](https://user-images.githubusercontent.com/101620299/194814383-227f796a-32f3-40f7-8cef-47acf4121783.png)
  
  please help

**Comment by ovear** [comment]
Duplicated issue, please try my fork instead.

**Comment by ubantos2** [comment]
Thx man, after downloading new fixed script from your "ovear" Fork really worked
