### ISSUE TITLE
adding a proxy option?

### ISSUE THREAD

**Issue by catshitz** [AlphaSlayer1964/kemono-dl#157]
### Description
`--proxy http://127.0.0.1:7890`

### Additional comments
like in yt-dlp

**Comment by suoyilong** [comment]
you can do this,
modify main.py, add a variate `proxies = {"https": "127.0.0.1:7890"}`
and add the option `proxies=proxies` to every `self.session.get` like :
`self.session.get(url=creators_api, cookies=self.cookies, headers=self.headers, proxies=proxies, timeout=self.timeout).json()`

it works for me

**Comment by catshitz** [comment]
> 

感谢 cli 临时和永久代理是知道的 只是除clash内开启外 在别处打开的windows terminal内同指令总代理不上😅

**Comment by suoyilong** [comment]
管理员模式下设置powershell代理
```
netsh winhttp set proxy 127.0.0.1:7890
netsh winhttps set proxy 127.0.0.1:7890
```
管理员模式下取消代理
`netsh winhttp reset proxy`

**Comment by suoyilong** [comment]
python是不走cmd或者powershell代理的。你要是用wsl的话倒是可以用windows代理
