### ISSUE TITLE
Unable to load cookie

### ISSUE THREAD

**Issue by cghctommyho** [AlphaSlayer1964/kemono-dl#167]
I am new. I have copy the cookie text in request header from chrome to a file "kemono.party_cookies.txt" . Those text is start with __ddg1_= and end by _pk_ses.1.5bc1=1.
Then got below output after excuse  
py kemono-dl.py --cookies kemono.party_cookies.txt --links https://kemono.party/fanbox/user/3316400.

Unable to load cookie kemono.party_cookies.txt
No cookies loaded | exiting

May I know is the cookie text correct and what should I do.

**Comment by ovear** [comment]
Try this plugin to export cookie.
https://chrome.google.com/webstore/detail/get-cookiestxt/bgaddhkoddajcdgocldbbfleckgcbcid

**Comment by cghctommyho** [comment]
> Try this plugin to export cookie. https://chrome.google.com/webstore/detail/get-cookiestxt/bgaddhkoddajcdgocldbbfleckgcbcid

It works. thx!
