### ISSUE TITLE
Warning: URL is not Downloadable

### ISSUE THREAD

**Issue by Rit76Horizon** [AlphaSlayer1964/kemono-dl#173]
### Version
Version: 2022.04.28

### Your Command
python kemono-dl.py --verbose --cookies "cookie.txt" --links https://www.kemono.party/fantia/user/47415

### Description of bug
When attempting to download from this URL I get a warning/error about it not being downloadable.

### How To Reproduce
Input the URL and attempt to run

### Error messages and tracebacks
WARNING:URL is not downloadable | https://www.kemono.party/fantia/user/47415
ERROR:No creator information was retrieved. | exiting

### Additional comments
Not sure if this URL is simply blocked from having anything downloaded. All posts result in the same warning/error. It comes up first when downloading --from-file. The debug log show's information I've already presented, but it's stated I must attach the debug log so it's below.

[debug.log](https://github.com/AlphaSlayer1964/kemono-dl/files/10318758/debug.log)

**Comment by L4cache** [comment]
remove www. from the link will work, i guess.
