### ISSUE TITLE
[FEATURE REQ] Read from config file

### ISSUE THREAD

**Issue by afterdelight** [AlphaSlayer1964/kemono-dl#93]
### Description
Add command to read default config from config file

Its a hassle to write again and again for many downlaods.

### Additional comments
Example: config file name: kemono_config
--read-config kemono_config

kemono_config(txt file) will have commands such as examples:(seperated by new lines)
--cookies kemono.party_cookies.txt 
--from-file gumroad_aroma.txt

unless the command overriden with the new value. it will use the default value from config file.

**Comment by AlphaSlayer1964** [comment]
For now use a batch/bash file to run your command.

**Comment by afterdelight** [comment]
i already use a cmd file on windows to run the commands. since the new update fucked my cmd bats. now i have to fix 8 cmd bats which is a hassle.

**Comment by AlphaSlayer1964** [comment]
Can I ask why you need multiple bat files? You should be able to set a variable in the bat file that is all the options you want in every command.
```bash
OPTIONS = your_args
python kemono-dl %OPTIONS --links link
python kemono-dl %OPTIONS --links link2
```
I believe that is the syntax

**Comment by AlphaSlayer1964** [comment]
Ok I'll look into adding an option to read from a config file.
