### ISSUE TITLE
ModuleNotFoundError: No module named 'PIL'

### ISSUE THREAD

**Issue by Sohzph** [AlphaSlayer1964/kemono-dl#94]
I installed the requirements with `pip install -r requirements.txt` all done correctly, but then I get this error when trying to download.
```
Traceback (most recent call last):
  File "D:\kemono-dl-2022.04.18.1\kemono-dl.py", line 1, in <module>
    from src.main import main
  File "D:\kemono-dl-2022.04.18.1\src\main.py", line 8, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
```
How to fix this?

PS: I already used this a week ago and had no problems, I had the latest version of Python 3 installed. Yesterday I did a new Windows installation, installed the latest version of Python 3 and get this error.

**Comment by Sohzph** [comment]
Solved by installing:

```
 pip install pillow 
 pip install image 
```

**Comment by AlphaSlayer1964** [comment]
` pip install image` should not be required.
