### ISSUE TITLE
script doesnt check hash value anymore

### ISSUE THREAD

**Issue by afterdelight** [AlphaSlayer1964/kemono-dl#95]
### Description
script doesnt check hash value anymore unlike previous version

### Additional comments
Please add the feature back, so it can check for corrupt downloads. ty

**Comment by AlphaSlayer1964** [comment]
Yes it does. That feature was never removed.

**Comment by afterdelight** [comment]
i renamed .part download file to .zip while it only downloaded 10%. the next time i launched the script it skipped and said as already downloaded while the file in fact is corrupted.

**Comment by AlphaSlayer1964** [comment]
It removes the .part when the file is done and has the correct hash. If you change it manually it assumes it downloaded it correctly already.

**Comment by afterdelight** [comment]
i exchanged the .part file with other file and it resume download without checking hash the file will be corrupted when i t complete. pls fix it.

**Comment by AlphaSlayer1964** [comment]
Why are you doing that?

**Comment by afterdelight** [comment]
because i want to check the script is checking the hash or not?

**Comment by afterdelight** [comment]
i want to skip large psd file so I rename big psd .part file to .zip

**Comment by afterdelight** [comment]
but it doesnt check hash when it resume download?

**Comment by AlphaSlayer1964** [comment]
Yes it does

**Comment by afterdelight** [comment]
uhh no it didnt i swapped the names with other file and it resume the download normally without error log

**Comment by AlphaSlayer1964** [comment]
I just tried your scenario and it says the file hash was incorrect.

**Comment by afterdelight** [comment]
![image](https://user-images.githubusercontent.com/39585663/165873044-718e3df1-1519-4444-8430-30f51902c264.png)

**Comment by AlphaSlayer1964** [comment]
These images do not show me anything.

**Comment by afterdelight** [comment]
real downlaoded part file 1,7 gb, fake replaced file 370mb. then when i resume it resume from 400mb which is from 370mb file. as you can see it didnt show error log

**Comment by AlphaSlayer1964** [comment]
Do you want it to check the hash before it resumes?

**Comment by afterdelight** [comment]
that was the real file it increased from 370mb to 540 mb after resume

**Comment by afterdelight** [comment]
yes, make it check hash file before it resume

**Comment by AlphaSlayer1964** [comment]
These images are not the debug.log

**Comment by AlphaSlayer1964** [comment]
> yes, make it check hash file before it resume

What hash am I comparing it to then? The server only gives me a completed files hash.

**Comment by AlphaSlayer1964** [comment]
> then u lied about it checking hash before resume download wtf

I never said that. When you said this:

> but it doesnt check hash when it resume download?

I said yes because it checks when done. Why would I think before the resume starts? Thats not possible.

**Comment by afterdelight** [comment]
but when it trying to resume i didnt get haash error as the picture above

**Comment by AlphaSlayer1964** [comment]
When it has "completed" it will tell you if the hash is wrong.

**Comment by AlphaSlayer1964** [comment]
I can not do any more unless you post a debug.log file.

**Comment by afterdelight** [comment]
pls add skip word filter instead so i can skip big psd files

**Comment by AlphaSlayer1964** [comment]
use `--verbose`

**Comment by AlphaSlayer1964** [comment]
> pls add skip word filter instead so i can skip big psd files

Make a pull request

**Comment by afterdelight** [comment]
i dont know how to code sory

**Comment by afterdelight** [comment]
now it shows verbose log
INFO:Downloading: [20220427] [FVBAH] [2] Tier 3 (PAGES HERE) .zip
DEBUG:Downloading from: https://kemono.party/data/44/f7/44f72820340a976ae166d91c973921bf993eba19b6829b1eb6e8efcf62583d22.zip?f=Tier 3 (PAGES HERE) .zip
DEBUG:Downloading to: kemono.party\gumroad\Aroma Sensei [4487698848613]\Pack 47 November 2021\[20220427] [FVBAH] [2] Tier 3 (PAGES HERE) .zip.part
INFO:Trying to resuming partial download | Resume size: 539321792 bytes
WARNING:Failed to download: [20220427] [FVBAH] [2] Tier 3 (PAGES HERE) .zip | 416 Range Not Satisfiable | Assuming broken server hash value
ERROR:Incorrect amount of bytes downloaded | Something went so wrong I have no idea what happened

**Comment by AlphaSlayer1964** [comment]
I wouldn't use the main but stick to the releases.

**Comment by afterdelight** [comment]
wdym by that

**Comment by AlphaSlayer1964** [comment]
how did you download the downloader? from releases?

**Comment by afterdelight** [comment]
i downloaded it from hre
https://github.com/AlphaSlayer1964/kemono-dl/archive/refs/heads/main.zip

**Comment by afterdelight** [comment]
so i can get the latest release

**Comment by AlphaSlayer1964** [comment]
Use the latest release from releases not main. I can not grantee everything works in main. But either way the file would have never been marked as completed and had the .part removed.

**Comment by AlphaSlayer1964** [comment]
Annoyingly some of the hashes on kemonos website are wrong so it could be correct but the hash on the server is wrong.

**Comment by afterdelight** [comment]
no it was the .rar file is corrupted when i opened it not wrong hash file. it was completed already an the .part file has been removed

**Comment by AlphaSlayer1964** [comment]
send link to post

**Comment by afterdelight** [comment]
i forgot already, too many files. it was kidmo on gumroad. a few gb file size. but i forgot which file
