### ISSUE TITLE
Mislined folder

### ISSUE THREAD

**Issue by afterdelight** [AlphaSlayer1964/kemono-dl#97]
### Version
Version: latest

### Your Command
just a regular command

### Description of bug
Mislined folder compared from old version which is right and new version have a space in front of folder file name

### How To Reproduce
dunno

### Error messages and tracebacks
![image](https://user-images.githubusercontent.com/39585663/165956652-4846ac24-e733-474d-ad96-9311bc50751d.png)

**Comment by AlphaSlayer1964** [comment]
Just checked the api for both of them and they have a space in front of the title. 
https://kemono.party/api/gumroad/user/1199729197439/post/GTPO
https://kemono.party/api/gumroad/user/1199729197439/post/tnbcJ
look at "title"

**Comment by afterdelight** [comment]
is possible that it has been changed by the author? Because for the previous download it doesnt have a space

**Comment by afterdelight** [comment]
also can it be fixed with the script to remove the space

**Comment by afterdelight** [comment]
ok
