### ISSUE TITLE
file corruption

### ISSUE THREAD

**Issue by afterdelight** [AlphaSlayer1964/kemono-dl#98]
### Version
Version: latest

### Your Command

F:\downloader\kemono.party\kemono-dl-main>kemono-dl.py --cookies kemono.party_cookies.txt --links https://kemono.party/gumroad/user/4691786451290 --dirname-pattern "{site}/{service}/{username} [{user_id}]" --filename-pattern "{title}/[00000000] [{id}] [{index}] {filename}.{ext}" --other-filename-pattern "[00000000] [{id}] [0] {filename}.{ext}" --extract-links --banner --icon --yt-dlp --json --content --comments --inline --dms --skip-filetypes psd --post-timeout 2 --archive gumroad_kidmo_downloaded.txt

### Description of bug
file suddenly corrupted and deleted while downloading. already happened twice

### Error messages and tracebacks
![image](https://user-images.githubusercontent.com/39585663/166096663-9a386841-ac4f-4225-9ba3-272df33183c8.png)

**Comment by AlphaSlayer1964** [comment]
The file is not corrupted. Kemono party's servers suck and timeout randomly on large files. That is the program trying to resume the download when that happens. There is no fix for this as their servers are the ones causing the timeout. Also do not post screen shots! Post the debug.log file using verbose.

**Comment by afterdelight** [comment]
i already post the fix on pull merge
